### ISSUE TITLE
Custom HTTP headers

### ISSUE THREAD

**Issue by sylfabre** [overblog/GraphiQLBundle#13]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Version/Branch   | 0.1.0-BETA1

I'm trying to follow the instructions at https://github.com/overblog/GraphiQLBundle/blob/master/Resources/doc/custom-http-headers.md to use a custom HTTP header.

But I cannot find the right file to edit to override the default GraphiQL template.
I've tried to append the following code:
```
overblog_graphiql:
    template: "GraphiQL/index.html.twig"
```
to the following files:
- config/routes/dev/graphiql.yaml
- config/routes/dev/twig.yaml
- config/routes.yaml

I get every time the following error:
_The routing file "XXX" contains unsupported keys for "overblog_graphiql": "template"._

What is the right file to edit?
This info should be added to the doc as you have already done for the template with `{# templates/GraphiQL/index.html.twig #}`

**Comment by mcg-web** [comment]
I have updated the documentation to work with Symfony 4 template. thank you for you feedback!
