### ISSUE TITLE
Add tag for last changes

### ISSUE THREAD

**Issue by zidaneus** [overblog/GraphiQLBundle#33]
| Q                | A
| ---------------- | -----
| Version/Branch   | 0.2.1

Please add new tag for this commit - https://github.com/overblog/GraphiQLBundle/commit/1f7030574cb99dda2e1c8d24175c8dc89a5df865

**Comment by mcg-web** [comment]
Released in [v0.3.0](https://github.com/overblog/GraphiQLBundle/releases/tag/v0.3.0)
