### ISSUE TITLE
Symfony 7 support

### ISSUE THREAD

**Issue by victormacko** [overblog/GraphiQLBundle#39]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Version/Branch   | master

Symfony 7 just got released (yay!) the other day - would it be possible to have this package also updated accordingly so SF7 can be used with this component?
Not sure if it's just the composer.json file or something else as well would be needed.

Thanks so much for creating such a great component.

**Comment by Dipesh79** [comment]
@mcg-web can you please check this issue?

**Comment by anthonylex** [comment]
Is there any update on this getting finished?

**Comment by mcg-web** [comment]
released in v1.0.0
